# Site
repository: erik.bille/erikbille.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Erik Bille
title: Student
email: hello@bille.tech
website: https://bille.tech

# Social links
twitter_username: erikbille
github_username:  erikbille
instagram_username: erikbille
linkedin_username: erik-bille

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_6279.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm Erik, a student and Apple consultant currently working my way towards a bachelors degree in systems engineering at Edinburgh Napier University.

  I'm a calm, curious and dedicated person who likes to explore new open-source projects and tinker with my home lab setup. When not behind the keyboard you'll likely find me walking around in the city or hiking in the mountains outside of Edinburgh.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: Skills and certificates
Skills and certificates: | # this will include new lines to allow paragraphs

  I hold these certificates:
    - Apple ACSP 10.14
    - Jamf certified tech (Jamf 200)
    - Cisco Meraki Network Associate (CMNA)
    - Cambridge certificate in advanced English


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
